const express = require('express');
const router = express.Router();
const asyncErrorHandler = require('../service/asyncErrorHandler');
const { getPosts, createPosts, patchPost, deletePosts, deletePost } = require('../controllers/posts');
router.get('/', asyncErrorHandler(getPosts));
router.post('/', asyncErrorHandler(createPosts));
router.patch('/:id', asyncErrorHandler(patchPost));
router.delete('/', asyncErrorHandler(deletePosts));
router.delete('/:id', asyncErrorHandler(deletePost));
module.exports = router;